{{- if and .Values.acsenginecluster.resourcegroup .Values.acsenginecluster.azurespappid .Values.acsenginecluster.azurespsecret .Values.acsenginecluster.azuresptenantid .Values.acsenginecluster.kubeconfigprivatekey .Values.acsenginecluster.clientprivatekey -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
{{ include "labels.standard" . | indent 8 }}
        openai/do-not-drain: "true"
    spec:
{{- if .Values.rbac.install }}
      serviceAccountName: acs-engine-autoscaler
{{- end }}
      nodeSelector: 
        beta.kubernetes.io/os: linux
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: AZURE_SP_APP_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: azure-sp-app-id
        - name: AZURE_SP_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: azure-sp-secret
        - name: AZURE_SP_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: azure-sp-tenant-id
        - name: SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: subscription-id
        - name: KUBECONFIG_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: kubeconfig-private-key
        - name: CLIENT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: client-private-key
        - name: CA_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: ca-private-key
        - name: ETCD_CLIENT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" .}}
              key: etcd-client-private-key
        - name: ETCD_SERVER_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" .}}
              key: etcd-server-private-key
        - name: ETCD_PEER_PRIVATE_KEY_0
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" .}}
              key: etcd-peer-private-key-0
        command:
            - python
            - main.py
            - --resource-group
            - {{ .Values.acsenginecluster.resourcegroup }}
            {{- if .Values.acsenginecluster.acsdeployment }}
            - --acs-deployment
            - {{ .Values.acsenginecluster.acsdeployment }}
            {{- end }}
            {{- if .Values.acsenginecluster.sleeptime }}
            - --sleep
            - {{ .Values.acsenginecluster.sleeptime | quote }}
            {{- end }}
            {{- if .Values.acsenginecluster.ignorepools }}
            - --ignore-pools 
            - {{ .Values.acsenginecluster.ignorepools }}
            {{- end }}
            {{- if .Values.acsenginecluster.spareagents }}
            - --spare-agents 
            - {{ .Values.acsenginecluster.spareagents | quote }}
            {{- end }}
            {{- if .Values.acsenginecluster.idlethreshold }}
            - --idle-threshold 
            - {{ .Values.acsenginecluster.idlethreshold | quote }}
            {{- end }}
            {{- if .Values.acsenginecluster.overprovision }}
            - --over-provision 
            - {{ .Values.acsenginecluster.overprovision | quote }}
            {{- end }}
            - -vvv
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Always
      dnsPolicy: Default
{{ end }}
